<a href="https://colab.research.google.com/github/sundarp17/Recommendation-Systems/blob/main/popularity_based_recommender_systems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
frame = pd.read_csv(r'/content/rating_final.csv')
cuisine = pd.read_csv(r'/content/chefmozcuisine.csv')

In [4]:
frame.head()

userID  placeID  rating  food_rating  service_rating
0  U1077   135085       2            2               2
1  U1077   135038       2            2               1
2  U1077   132825       2            2               2
3  U1077   135060       1            2               2
4  U1068   135104       1            1               2

In [5]:
cuisine.head()

placeID        Rcuisine
0   135110         Spanish
1   135109         Italian
2   135107  Latin_American
3   135106         Mexican
4   135105       Fast_Food

Recommending the place based on counts

In [7]:
rating_count = pd.DataFrame(frame.groupby('placeID')['rating'].count())
rating_count.sort_values('rating',ascending=False).head()

rating
placeID        
135085       36
132825       32
135032       28
135052       25
132834       25

In [8]:
most_rated_places = pd.DataFrame([135085,132825,135032,135052,132834],index=np.arange(5),columns=['placeID'])

summary = pd.merge(most_rated_places,cuisine,on='placeID')
summary

placeID         Rcuisine
0   135085        Fast_Food
1   132825          Mexican
2   135032        Cafeteria
3   135032     Contemporary
4   135052              Bar
5   135052  Bar_Pub_Brewery
6   132834          Mexican

In [13]:
cuisine['Rcuisine'].describe()

count         916
unique         59
top       Mexican
freq          239
Name: Rcuisine, dtype: object

We can say that mexican food is best food and places 132825, 132834 are recommended for users.